twig:
    paths:
      '%kernel.project_dir%/templates':
      '%kernel.project_dir%/vendor/easycorp/easyadmin-bundle/src': easyadmin
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
